ws_url: ws://0.0.0.0:8900
commitment: confirmed

program:
  id: "11111111111111111111111111111111"
  idl: ./samples/idl.json
  account_notifications: "11111111111111111111111111111111"
  log_notifications: true
  program_notifications: false

sinks:
  - type: stdout
    format: json
  # - type: file
  #   path: ./events.jsonl
  # - type: pubsub
  #   credentials_file: ./gcp.json
  #   project_id: abc123
  #   topic: estuary-test
  # - type: webhook
  #   url: https://webhook.site/...
  # - type: sqs
  #   queue_url: http://localhost:9324/000000000000/estuary-test
  #   endpoint_url: http://localhost:9324
  #   region: elasticmq
  # - type: rabbitmq
  #   url: amqp://localhost:5672
  #   queue: estuary-test
