services:
  # estuary:
  #   image: estuary:latest
  #   container_name: estuary
  #   environment:
  #     ESTUARY_CONFIG: /estuary/.estuaryrc.yaml
  #   extra_hosts:
  #     - host.docker.internal:host-gateway
  #   volumes:
  #     - ./samples:/estuary/samples
  #     - ./.estuaryrc.yaml:/estuary/.estuaryrc.yaml:ro

  # elasticmq:
  #   image: softwaremill/elasticmq-native:latest
  #   ports:
  #     - "9324:9324"
  #     - "9325:9325"
  #   volumes:
  #     - ./samples/elasticmq.conf:/opt/elasticmq.conf
  #
  # elasticmq-ui:
  #   image: softwaremill/elasticmq-ui:latest
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     SQS_ENDPOINT: http://elasticmq:9324
  #   depends_on:
  #     - elasticmq

  # rabbitmq:
  #   image: rabbitmq:4-management
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

  pubsub:
    image: google/cloud-sdk:emulators
    container_name: pubsub
    entrypoint: gcloud
    command:
      [
        "beta",
        "emulators",
        "pubsub",
        "start",
        "--project=abc123",
        "--host-port=0.0.0.0:8085",
      ]
    ports:
      - "8085:8085"

  # kafka:
  #   image: apache/kafka:latest
  #   container_name: kafka
  #   ports:
  #     - "9092:9092"
  #     - "9093:9093"
  #   environment:
  #     KAFKA_NODE_ID: 1
  #     KAFKA_PROCESS_ROLES: broker,controller
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  #     KAFKA_LOG_DIRS: /var/lib/kafka/data
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLED: "true"
  #     KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 1
  #   volumes:
  #     - ./kafka:/var/lib/kafka/data
